CREATE TABLE event
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id UUID         NOT NULL DEFAULT gen_random_uuid(),
    name        VARCHAR(255) NOT NULL,
    type        VARCHAR(255) NOT NULL,
    description TEXT,
    organizer   VARCHAR(255) NOT NULL,
    location    VARCHAR(255) NOT NULL,
    start_date  TIMESTAMPTZ,
    end_date    TIMESTAMPTZ,

    CONSTRAINT uk_event_external_id UNIQUE (external_id)
);