-- Table name "user" is reserved in PostgreSQL, so we chose "app_user" instead.

CREATE TABLE app_user
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id   UUID         NOT NULL DEFAULT gen_random_uuid(),
    name          VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,

    CONSTRAINT uk_app_user_email UNIQUE (email),
    CONSTRAINT uk_app_user_external_id UNIQUE (external_id)
);