CREATE TABLE event
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id UUID         NOT NULL DEFAULT gen_random_uuid(),
    owner_id    BIGINT       NOT NULL,
    name        VARCHAR(255) NOT NULL,
    type        event_type   NOT NULL,
    description TEXT,
    organizer   VARCHAR(255) NOT NULL,
    location    VARCHAR(255) NOT NULL,
    start_date  TIMESTAMPTZ  NOT NULL,
    end_date    TIMESTAMPTZ,

    CONSTRAINT fk_event_owner FOREIGN KEY (owner_id)
        REFERENCES app_user (id)
        ON DELETE CASCADE,

    CONSTRAINT uk_event_external_id UNIQUE (external_id),
    CONSTRAINT chk_end_date CHECK (end_date >= start_date)
);

CREATE INDEX idx_event_owner_id ON event (owner_id);